version: 2
project_name: vscode-lsps

builds:
  # VSCode Eslint
  - id: eslint
    binary: eslint-lsp
    main: ./cmd/eslint-lsp
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: eslint
    builds:
      - eslint-lsp
    name_template: "eslint-lsp_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
        README.md
        out/eslint/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: matzxrr
    name: vscode-lsp
  prerelease: auto
  draft: true
